export const LUDO_TREASURY_ABI = [
  'constructor(address _usdtToken, address _treasuryWallet, address _relayerOracle)',
  'event DepositReceived(address indexed player, uint256 amount, uint256 newBalance)',
  'event MatchCreated(string indexed matchId, uint256 entryFee)',
  'event PlayerJoinedMatch(string indexed matchId, address indexed player, uint256 entryFee)',
  'event MatchSettled(string indexed matchId, address indexed winner, uint256 winnerPayout, uint256 platformRake, uint256 timestamp)',
  'event MatchRefunded(string indexed matchId, uint256 refundPerPlayer)',
  'event WithdrawalDispatched(address indexed recipient, uint256 grossAmount, uint256 netAmount, uint256 totalFeesDeducted, string destinationChain)',
  'event TreasuryUpdated(address indexed oldTreasury, address indexed newTreasury)',
  'event RelayerUpdated(address indexed oldRelayer, address indexed newRelayer)',
  'function depositUsdt(uint256 amount) external',
  'function joinMatchWithSignature(address player, string matchId, uint256 entryFee, uint256 deadline, bytes signature) external',
  'function settleMatch(string matchId, address winner, uint256 winnerPayout, uint256 platformRake) external',
  'function cancelMatchAndRefund(string matchId) external',
  'function executeWithdrawal(address recipient, uint256 grossAmount, uint256 totalFeesDeducted, string destinationChain) external',
  'function vaultBalances(address player) external view returns (uint256)',
  'function nonces(address player) external view returns (uint256)',
  'function matchEscrows(string matchId) external view returns (string matchId, uint256 entryFee, uint256 totalEscrowed, bool isSettled, bool isCancelled, address winner, uint256 winnerPayout, uint256 platformRake)',
  'function DOMAIN_SEPARATOR() external view returns (bytes32)',
  'function treasuryWallet() external view returns (address)',
  'function relayerOracle() external view returns (address)',
  'function owner() external view returns (address)',
];

export const ERC20_ABI = [
  'function name() external view returns (string)',
  'function symbol() external view returns (string)',
  'function decimals() external view returns (uint8)',
  'function totalSupply() external view returns (uint256)',
  'function balanceOf(address account) external view returns (uint256)',
  'function transfer(address recipient, uint256 amount) external returns (bool)',
  'function allowance(address owner, address spender) external view returns (uint256)',
  'function approve(address spender, uint256 amount) external returns (bool)',
  'function transferFrom(address sender, address recipient, uint256 amount) external returns (bool)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
  'event Approval(address indexed owner, address indexed spender, uint256 value)',
];
